rg_name             = "cmaz-eh8dj90z-mod3-rg"
location            = "eastus"
storageaccount_name = "cmazeh8dj90zsa"
vnet_name           = "cmaz-eh8dj90z-mod3-vnet"
subnet1_name        = "frontend"
subnet2_name        = "backend"
student_email       = "suryansh_tilak@epam.com"
